// <auto-generated />
namespace FirstLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addPdfbooks3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPdfbooks3));
        
        string IMigrationMetadata.Id
        {
            get { return "201912191803596_addPdfbooks3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
